ward_leonard_disco_title:
    resource: "@WardLeonardDiscoBundle/Controller/TitleController.php"
    type:     annotation

ward_leonard_disco_lyric:
    resource: "@WardLeonardDiscoBundle/Controller/LyricController.php"
    type:     annotation

ward_leonard_disco_disk:
    resource: "@WardLeonardDiscoBundle/Controller/DiskController.php"
    type:     annotation


ward_leonard_group:
    resource: "@WardLeonardGroupBundle/Controller/"
    type:     annotation
    prefix:   /group

ward_leonard_disco:
    resource: "@WardLeonardDiscoBundle/Controller/"
    type:     annotation
    prefix:   /disco

ward_leonard_news:
    resource: "@WardLeonardNewsBundle/Controller/"
    type:     annotation
    prefix:   /news

