ward_leonard_disco:
    resource: "@WardLeonardDiscoBundle/Controller/"
    type:     annotation
    prefix:   /disco

ward_leonard_news:
    resource: "@WardLeonardNewsBundle/Controller/"
    type:     annotation
    prefix:   /

